services:
  web:
    restart: unless-stopped
    # command: bash -c "yarn && pm2-runtime dist/web/main.js -i max"
    command: sleep 10000

  api:
    restart: unless-stopped
    # command: bash -c "yarn && pm2-runtime dist/web/main.js -i max"
    command: sleep 10000

  workers:
    restart: unless-stopped

  nginx:
    restart: unless-stopped

  mysql:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  clickhouse:
    restart: unless-stopped
